import assert from 'node:assert/strict'
import { scheduledTvGame } from '../src/lib/scheduledTvGame'
const times = new Map([[1, { startsAt: 100, endsAt: 200 }], [2, { startsAt: 250, endsAt: 350 }], [3, { startsAt: 400, endsAt: 500 }]])
const games = [1, 2, 3]
assert.equal(scheduledTvGame(99, games, times), undefined)
assert.equal(scheduledTvGame(100, games, times), 1)
assert.equal(scheduledTvGame(199, games, times), 1)
assert.equal(scheduledTvGame(200, games, times), 2)
assert.equal(scheduledTvGame(249, games, times), 2)
assert.equal(scheduledTvGame(250, games, times), 2)
assert.equal(scheduledTvGame(350, games, times), 3)
assert.equal(scheduledTvGame(450, games, times), 3)
assert.equal(scheduledTvGame(500, games, times), 3)
assert.equal(scheduledTvGame(900, games, times), 3)
assert.equal(scheduledTvGame(250, games), undefined)
assert.equal(scheduledTvGame(250, [1], times), 1)
assert.equal(scheduledTvGame(250, [], times), undefined)
assert.equal(scheduledTvGame(250, [3, 1, 2], times), 2)
assert.equal(scheduledTvGame(NaN, games, times), undefined)
assert.equal(scheduledTvGame(250, games, new Map([[1, { startsAt: NaN, endsAt: 200 }]])), undefined)
const continuous = new Map([[1, { startsAt: 100, endsAt: 200 }], [2, { startsAt: 200, endsAt: 300 }]])
assert.equal(scheduledTvGame(200, [1, 2], continuous), 2)
console.log('All-screen end boundaries, breaks, wake-up catch-up, final game, and invalid schedules passed')
